databases:
  - name: cube-saas-postgres
    databaseName: cube_saas
    user: cube_user
    region: frankfurt
    ipAllowList: []

services:
  - type: web
    name: cube-management-contract-saas
    env: docker
    region: frankfurt
    plan: free
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: cube-saas-postgres
          property: connectionString
      - key: UPLOAD_DIR
        value: /app/uploads
